### ISSUE TITLE
excel para json

### ISSUE THREAD

**Issue by Ana-CAS-Machado** [sepep-pmsp/planos_setoriais#68]
- [ ] Criar uma pasta para colocar o Excel dos Planos
- [ ] Criar um script para acessar o Excel
- [ ] Transformar o Excel em Json

**Comment by brunoazuma** [comment]
Desde o início do projeto o catálogo dos planos mudou apenas uma vez, reduzindo a necessidade desse script. Caso a necessidade se mostre importante novamente, uma nova issue será aberta
